### PR TITLE
Add the start of an offboarding checklist

### PR DESCRIPTION
**Pull request by PeterJCLaw**
This is likely very incomplete, however provides a place for us to start adding things as we discover them.

The scope here is really the checklist of services, so it is explicitly _not_ the scope of this PR to make this checklist a complete guide for offboarding. (That would be great to do, but separately).

Fixes https://github.com/srobo/infrastructure-team-minutes/issues/12

### CODE REVIEW

**Comment by trickeydan** [comment]
Drive-by thought: We should probably be asking for equipment back too?

**Comment by Tyler-Ward** [comment]
We should also consider different levels of offboarding e.g. fully leaving vs taking a less active role or a single small role e.g. mentoring only

**Comment by PeterJCLaw** [comment]
> We should also consider different levels of offboarding e.g. fully leaving vs taking a less active role or a single small role e.g. mentoring only

Definitely, though for now I'm trying to keep this simple so as to get the basics in place.

-----

@sedders123 @antoinepetty adding you as reviewers here as you've mostly been doing the onboarding of volunteers recently so may have some thoughts.

ping @dianedowling if you have thoughts too.

I'd quite like to get this in soon, so that we have a record of the linked spreadsheet and so that we have something in place to start improving.

**Comment by sedders123** [comment]
Is the intent of this PR to replace the [Volunteer Management](https://github.com/srobo/ops-manual/wiki/Volunteer-Management) part of the ops-manual wiki? Seems like we may be making two places to look for information on offboarding. Personally, I think the runbook is likely the correct place for this but there is a lot of info in the wiki already (though it could well be outdated as our processes have changed). Do we want to copy the info from the wiki here or are we intentionally starting again?

**Comment by PeterJCLaw** [comment]
Huh, I wasn't aware/had forgotten about that. My goal here was primarily to have a place to put the link to the services spreadsheet and it kinda snowballed a bit from there. There's definitely a lot of overlap here.

As part of the Infrastructure Team's responsibility to ensure access to services we probably need to have input into the off-boarding procedures, though that may only need to be something like "check the sheet to see what services the person needs to hand over".

I'll review those docs more and maybe put together an ops-manual PR.
Agree that maybe some of that might fit better in the runbook.

**Comment by PeterJCLaw** [comment]
For visibility: I've raised the interaction with the ops-manual in https://github.com/srobo/ops-manual/issues/21, which the trustees are going to review (along with the other open ops manual issues) in their next meeting.

**Comment by PeterJCLaw** [comment]
The conclusion on the ops manual seems to be that:
- this sort of content is a good fit for the runbook, so let's keep it here
- the wiki isn't something the current trustees were aware of; they're going to review it but likely it'll change somewhat

I therefore suggest that we move forwads with this PR as starting the new home for this sort of information and if things change we can update it to reflect that.

**Review by sedders123 — APPROVED** [review]

**Pull request merged**
